"""Orchestrator — Gemini via LiteLLM, with an A2AAgent wrapped as a tool.

This process is the entry point of the use case. It receives the user's query
and, based on its content, decides (via the system prompt) whether to resolve it
directly with Gemini or delegate the sensitive portion to the local remote agent
through the `handle_sensitive_query` tool.

The tool wraps an `A2AAgent` that talks, over HTTP/JSON-RPC, to the `A2AServer`
running in another process (remote_agent/server.py).

Requires the remote server to already be running. Run:
    python -m orchestrator.main            # interactive mode
    python -m orchestrator.main "query"    # single query
"""

import asyncio
import sys

from strands import Agent, tool
from strands.agent.a2a_agent import A2AAgent
from strands.models.litellm import LiteLLMModel

from common.config import load_orchestrator_config
from common.logging_config import setup_logging
from common.prompts import ORCHESTRATOR_SYSTEM_PROMPT

logger = setup_logging("orchestrator.log", "orchestrator")

_config = load_orchestrator_config()

# A2A client toward the local remote agent. Created once and reused.
# The interface is the same as a local Agent: you invoke it and it returns an
# AgentResult. The A2A protocol stays hidden behind this abstraction.
_remote_agent = A2AAgent(
    endpoint=_config.remote_agent_url,
    name="local_privacy_agent",
)


def _delegate_to_local_agent(query: str) -> str:
    """Actual delegation logic behind the tool.

    Kept as a plain function (not the @tool-wrapped one) so it can be called
    and tested directly, without depending on Strands' tool wrapper internals.
    """
    logger.info("DELEGATING to local agent via A2A -> %s", _config.remote_agent_url)
    logger.debug("Delegated payload (sensitive context): %s", query)

    result = _remote_agent(query)
    text = result.message["content"][0]["text"]

    logger.info("A2A response received from local agent (%d chars)", len(text))
    return text


@tool
def handle_sensitive_query(query: str) -> str:
    """Process a query with sensitive data on a 100% local agent.

    Use this tool when the user's query contains or requires handling sensitive
    data (account or card numbers, national ID, balances, medical information,
    credentials, etc.). Processing happens on a local agent (Gemma via Ollama)
    without the data leaving the machine.

    Args:
        query: the text of the user's query to process locally.

    Returns:
        The response generated by the local agent.
    """
    return _delegate_to_local_agent(query)


def build_orchestrator() -> Agent:
    """Build the orchestrator Agent (Gemini + A2A tool). Separated for tests."""
    model = LiteLLMModel(
        client_args={"api_key": _config.gemini_api_key},
        model_id=_config.model_id,
        params={
            # Temperature comes from the .env (ORCHESTRATOR_TEMPERATURE). It
            # stays valid and useful for the many other providers LiteLLM
            # supports (Anthropic, OpenAI, Bedrock, etc.) if you swap
            # ORCHESTRATOR_MODEL_ID. On Gemini 3+ it only triggers a harmless
            # deprecation warning.
            "temperature": _config.temperature,
            # Automatic retries on transient errors (e.g. 503 "high demand",
            # 429 rate limit). LiteLLM retries the completion up to num_retries
            # times with backoff before raising. Cloud APIs fail transiently, so
            # this makes the orchestrator noticeably more robust.
            "num_retries": 2,
        },
    )
    return Agent(
        name="Customer Support Orchestrator",
        model=model,
        system_prompt=ORCHESTRATOR_SYSTEM_PROMPT,
        tools=[handle_sensitive_query],
        # Disable the default callback handler: we stream the answer ourselves
        # via stream_async (see run_once) to print it token by token. Leaving
        # the default handler on would print the same text a second time.
        callback_handler=None,
    )


async def run_once(orchestrator: Agent, query: str) -> str:
    """Stream a single query token by token and return the full response text.

    We iterate the agent's async event stream instead of calling it directly:
    - `event["data"]` carries each text chunk as it is generated; we print it
      immediately so the user sees the answer flow in real time.
    - the final `event["result"]` carries the AgentResult; we read the complete
      message from it and return it (useful for tests and for callers that need
      the string, not just the console output).
    """
    logger.info("Query received: %s", query)

    response = ""
    print("Assistant> ", end="", flush=True)
    async for event in orchestrator.stream_async(query):
        if "data" in event:
            print(event["data"], end="", flush=True)
        elif "result" in event:
            response = event["result"].message["content"][0]["text"]
    print()  # newline after the streamed answer

    logger.info("Final response to user emitted (%d chars)", len(response))
    return response


async def _interactive_loop(orchestrator: Agent) -> None:
    print("Customer-support assistant. Type 'exit' to quit.\n")
    while True:
        try:
            query = input("You> ").strip()
        except (EOFError, KeyboardInterrupt):
            print()
            break
        if query.lower() in {"exit", "quit", "salir"}:
            break
        if not query:
            continue
        await run_once(orchestrator, query)
        print()


async def main() -> None:
    orchestrator = build_orchestrator()

    # If the query is passed as an argument, resolve it a single time.
    if len(sys.argv) > 1:
        query = " ".join(sys.argv[1:])
        await run_once(orchestrator, query)
        return

    await _interactive_loop(orchestrator)


if __name__ == "__main__":
    asyncio.run(main())
